### ISSUE TITLE
Error after HA update

### ISSUE THREAD

**Issue by matisaul** [custom-cards/tracker-card#19]
Hi,

I'm getting this error after HA update. I'm using the lastest version for this card.

```
2018-09-29 11:50:13 ERROR (MainThread) [homeassistant.core] Error executing service <ServiceCall custom_updater.update_all (c:ab0cb83bf48d46b19147cdd0223f7847)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/core.py", line 1185, in _event_to_service_call
    await self._hass.async_add_executor_job(execute_service)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/core.py", line 1182, in execute_service
    service_handler.func(service_call)
  File "/config/custom_components/custom_updater.py", line 94, in update_all_service
    card_controller.update_all()
  File "/config/custom_components/custom_updater.py", line 199, in update_all
    if (self.hass.data[CARD_DATA][name]['has_update'] and
TypeError: list indices must be integers or slices, not str
```

**Comment by ludeeus** [comment]
This is not an issue with the card, but an issue with the component that are resolved in the newest version if it
