### ISSUE TITLE
custom_updater.update_all fails

### ISSUE THREAD

**Issue by shreram** [custom-cards/tracker-card#22]
There are new updates but a query to 'Update All' service throws following exceptions in the log file.

![image](https://user-images.githubusercontent.com/16169720/46419052-a22c5600-c6f2-11e8-9362-3c398fdee3ad.png)

I noticed this issue was fixed in custom updater 2.7.3 but I couldn't get that version via GUI.
https://github.com/custom-components/custom_updater/releases/tag/2.7.3

Do I have to manually get updated files to fix this issue? 

```
2018-10-03 09:47:28 ERROR (MainThread) [frontend.js.latest.201809270] http://192.168.86.226:8123/frontend_latest/app-084b7564.js:2856:640 Uncaught TypeError: Cannot read property '_stateDisplay' of null
2018-10-03 09:47:28 ERROR (MainThread) [frontend.js.latest.201809270] http://192.168.86.226:8123/frontend_latest/app-084b7564.js:2856:640 Uncaught TypeError: Cannot read property '_stateDisplay' of null
2018-10-03 09:47:28 ERROR (MainThread) [frontend.js.latest.201809270] http://192.168.86.226:8123/frontend_latest/app-084b7564.js:2856:640 Uncaught TypeError: Cannot read property '_stateDisplay' of null
2018-10-03 09:47:28 ERROR (MainThread) [frontend.js.latest.201809270] http://192.168.86.226:8123/frontend_latest/app-084b7564.js:2856:640 Uncaught TypeError: Cannot read property '_stateDisplay' of null
2018-10-03 09:47:28 ERROR (MainThread) [frontend.js.latest.201809270] http://192.168.86.226:8123/frontend_latest/app-084b7564.js:2856:640 Uncaught TypeError: Cannot read property '_stateDisplay' of null
2018-10-03 09:47:28 ERROR (MainThread) [frontend.js.latest.201809270] http://192.168.86.226:8123/frontend_latest/app-084b7564.js:2856:640 Uncaught TypeError: Cannot read property '_stateDisplay' of null
2018-10-03 09:47:28 ERROR (MainThread) [frontend.js.latest.201809270] http://192.168.86.226:8123/frontend_latest/app-084b7564.js:2856:640 Uncaught TypeError: Cannot read property '_stateDisplay' of null
2018-10-03 09:47:28 ERROR (MainThread) [frontend.js.latest.201809270] http://192.168.86.226:8123/frontend_latest/app-084b7564.js:2856:640 Uncaught TypeError: Cannot read property '_stateDisplay' of null
2018-10-03 09:47:28 ERROR (MainThread) [frontend.js.latest.201809270] http://192.168.86.226:8123/frontend_latest/app-084b7564.js:2856:640 Uncaught TypeError: Cannot read property '_stateDisplay' of null
2018-10-03 09:47:28 ERROR (MainThread) [frontend.js.latest.201809270] http://192.168.86.226:8123/frontend_latest/app-084b7564.js:2856:640 Uncaught TypeError: Cannot read property '_stateDisplay' of null
2018-10-03 09:47:28 ERROR (MainThread) [frontend.js.latest.201809270] http://192.168.86.226:8123/frontend_latest/app-084b7564.js:2856:640 Uncaught TypeError: Cannot read property '_stateDisplay' of null
2018-10-03 09:48:57 ERROR (MainThread) [homeassistant.core] Error executing service <ServiceCall custom_updater.update_all (c:5752af9cbc384ae2a72bd8648652e095)>
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/core.py", line 1185, in _event_to_service_call
    await self._hass.async_add_executor_job(execute_service)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/app/homeassistant/core.py", line 1182, in execute_service
    service_handler.func(service_call)
  File "/config/custom_components/custom_updater.py", line 94, in update_all_service
    card_controller.update_all()
  File "/config/custom_components/custom_updater.py", line 199, in update_all
    if (self.hass.data[CARD_DATA][name]['has_update'] and
TypeError: list indices must be integers or slices, not str
2018-10-03 09:48:57 ERROR (MainThread) [homeassistant.core] Error executing service <ServiceCall custom_updater.update_all (c:3749bbe286a045deb0d9c08debb6c44a)>
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/core.py", line 1185, in _event_to_service_call
    await self._hass.async_add_executor_job(execute_service)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/app/homeassistant/core.py", line 1182, in execute_service
    service_handler.func(service_call)
  File "/config/custom_components/custom_updater.py", line 94, in update_all_service
    card_controller.update_all()
  File "/config/custom_components/custom_updater.py", line 199, in update_all
    if (self.hass.data[CARD_DATA][name]['has_update'] and
TypeError: list indices must be integers or slices, not str

```

**Comment by ludeeus** [comment]
@shreram yes, the version you have of the `custom_updater` was broken AF...
sorry about that, the current version is more stable and faster.
Manually upgrading to that will fix this issue.
