### ISSUE TITLE
Custom components failed to load

### ISSUE THREAD

**Issue by shreram** [custom-cards/tracker-card#23]
I manually updated to latest custom_updater to resolve the  
[issue 22](https://github.com/custom-cards/tracker-card/issues/22) and was able to update all entities via 'Update All'. That was successful and later I restarted HA. 

Now I get this error message in the logs and UI doesn't show any entities.

```
2018-10-03 11:40:04 ERROR (MainThread) [homeassistant.setup] Error during setup of component custom_updater
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/setup.py", line 148, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/custom_updater.py", line 71, in setup
    config_show_installabe)
  File "/config/custom_components/custom_updater.py", line 167, in __init__
    from pyupdate.ha_custom import custom_components
ModuleNotFoundError: No module named 'pyupdate'

```
![image](https://user-images.githubusercontent.com/16169720/46425843-68fbe200-c702-11e8-8cff-15b1348a9378.png)

```
2018-10-03 11:40:57 ERROR (MainThread) [frontend.js.latest.201809270] http://192.168.86.226:8123/local/tracker-card.js?v=0.1.5:1:1 Uncaught SyntaxError: Identifier 'TrackerCard' has already been declared
2018-10-03 11:42:26 ERROR (MainThread) [frontend.js.latest.201809270] http://192.168.86.226:8123/frontend_latest/app-084b7564.js:2856:640 Uncaught TypeError: Cannot read property '_stateDisplay' of null
2018-10-03 11:42:26 ERROR (MainThread) [frontend.js.latest.201809270] http://192.168.86.226:8123/frontend_latest/app-084b7564.js:2856:640 Uncaught TypeError: Cannot read property '_stateDisplay' of null
2018-10-03 11:42:26 ERROR (MainThread) [frontend.js.latest.201809270] http://192.168.86.226:8123/frontend_latest/app-084b7564.js:2856:640 Uncaught TypeError: Cannot read property '_stateDisplay' of null
2018-10-03 11:42:26 ERROR (MainThread) [frontend.js.latest.201809270] http://192.168.86.226:8123/frontend_latest/app-084b7564.js:2856:640 Uncaught TypeError: Cannot read property '_stateDisplay' of null
2018-10-03 11:42:26 ERROR (MainThread) [frontend.js.latest.201809270] http://192.168.86.226:8123/frontend_latest/app-084b7564.js:2856:640 Uncaught TypeError: Cannot read property '_stateDisplay' of null
2018-10-03 11:42:26 ERROR (MainThread) [frontend.js.latest.201809270] http://192.168.86.226:8123/frontend_latest/app-084b7564.js:2856:640 Uncaught TypeError: Cannot read property '_stateDisplay' of null
2018-10-03 11:42:26 ERROR (MainThread) [frontend.js.latest.201809270] http://192.168.86.226:8123/frontend_latest/app-084b7564.js:2856:640 Uncaught TypeError: Cannot read property '_stateDisplay' of null
2018-10-03 11:42:26 ERROR (MainThread) [frontend.js.latest.201809270] http://192.168.86.226:8123/frontend_latest/app-084b7564.js:2856:640 Uncaught TypeError: Cannot read property '_stateDisplay' of null
2018-10-03 11:42:26 ERROR (MainThread) [frontend.js.latest.201809270] http://192.168.86.226:8123/frontend_latest/app-084b7564.js:2856:640 Uncaught TypeError: Cannot read property '_stateDisplay' of null
2018-10-03 11:42:26 ERROR (MainThread) [frontend.js.latest.201809270] http://192.168.86.226:8123/frontend_latest/app-084b7564.js:2856:640 Uncaught TypeError: Cannot read property '_stateDisplay' of null
2018-10-03 11:42:26 ERROR (MainThread) [frontend.js.latest.201809270] http://192.168.86.226:8123/frontend_latest/app-084b7564.js:2856:640 Uncaught TypeError: Cannot read property '_stateDisplay' of null
```

`2018-10-03 11:40:57 ERROR (MainThread) [frontend.js.latest.201809270] http://192.168.86.226:8123/local/tracker-card.js?v=0.1.5:1:1 Uncaught SyntaxError: Identifier 'TrackerCard' has already been declared
`

**Comment by ludeeus** [comment]
@shreram Unless you already have figured it out another restart of HA will fix that :)

**Comment by shreram** [comment]
It worked partially after HA restart. It doesn't refresh to get custom cards. I noticed same errors in the log file.

![image](https://user-images.githubusercontent.com/16169720/46431431-6bb20380-c711-11e8-931d-25fc0fd36ac3.png)

**Comment by ludeeus** [comment]
Nope not partially, that is by design ;)
<https://github.com/custom-components/custom_updater/wiki/Installation#configuration-option-track>
