### ISSUE TITLE
Using lovelace-gen.py breaks tracker-card

### ISSUE THREAD

**Issue by patrik996** [custom-cards/tracker-card#35]
Hi,
Just started testing lovelace-gen.py from https://github.com/thomasloven/homeassistant-lovelace-gen. 
lovelace-gen.py is used to split the ui-lovelace.yaml config for better management.

It seems to break the functionality of the tracker-card. It still lists my custom cards but nothing happens if i click on update_all.

Dont know if the problem is in lovelace-gen.py code or your code.

Any idea?

**Comment by patrik996** [comment]
It seems it might be in the custom_updater component not the tracker-card:

019-02-08 14:02:25 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140575107121896] Error handling message: {'type': 'call_service', 'domain': 'custom_updater', 'service': 'update_all', 'service_data': {}, 'id': 21}
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/components/websocket_api/decorators.py", line 17, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/app/homeassistant/components/websocket_api/commands.py", line 148, in handle_call_service
    connection.context(msg))
  File "/usr/src/app/homeassistant/core.py", line 1130, in async_call
    self._execute_service(handler, service_call))
  File "/usr/src/app/homeassistant/core.py", line 1154, in _execute_service
    await self._hass.async_add_executor_job(handler.func, service_call)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/custom_updater.py", line 94, in update_all_service
    card_controller.update_all()
  File "/config/custom_components/custom_updater.py", line 149, in update_all
    self.custom_url)
  File "/config/deps/lib/python3.6/site-packages/pyupdate/ha_custom/custom_cards.py", line 87, in update_all
    upgrade_single(base_dir, name, custom_repos)
  File "/config/deps/lib/python3.6/site-packages/pyupdate/ha_custom/custom_cards.py", line 97, in upgrade_single
    local_file = get_card_dir(base_dir, name) + name + '.js'
  File "/config/deps/lib/python3.6/site-packages/pyupdate/ha_custom/custom_cards.py", line 135, in get_card_dir
    card = line.split('!resource ')[1].split(name + '.js')
IndexError: list index out of range

**Comment by patrik996** [comment]
Closing this. There is an issue here:

https://github.com/thomasloven/homeassistant-lovelace-gen/issues/13
