### ISSUE TITLE
Custom updater failed

### ISSUE THREAD

**Issue by edoardop13** [custom-cards/tracker-card#38]
When I install custom updater I have this error:

`Error during setup of component custom_updater
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/setup.py", line 148, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/custom_updater.py", line 76, in setup
    config_show_installabe, conf_mode)
  File "/config/custom_components/custom_updater.py", line 147, in __init__
    self.ha_conf_dir, self.mode, conf_card_urls)
  File "/config/deps/lib/python3.6/site-packages/pyupdate/ha_custom/custom_cards.py", line 73, in init_local_data
    remote = get_info_all_cards(custom_repos)
  File "/config/deps/lib/python3.6/site-packages/pyupdate/ha_custom/custom_cards.py", line 53, in get_info_all_cards
    for name, card in response.json().items():
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.6/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

And have a error with new version "4.0.0". I have update the resources with "customcards" path but it does not find the files and I do not load the cards.

This is my configuration:
`custom_updater:
  show_installable: true
  card_urls:
    - https://raw.githubusercontent.com/custom-cards/tracker-card/master/tracker-card.js
    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json
    - https://raw.githubusercontent.com/thomasloven/lovelace-card-modder/master/card-modder.js
    - https://raw.githubusercontent.com/thomasloven/lovelace-card-tools/master/card-tools.js`

**Comment by ludeeus** [comment]
remove **ALL** lines ending with `.js`  from your config.

**Comment by edoardop13** [comment]
Why?

**Comment by ludeeus** [comment]
Because that breaks it, it expects json, you are giving it javascript.

https://github.com/custom-components/custom_updater/wiki/Installation#configuration-option-card_urls

_This part are considered advanced configuration, this option is here to provide support for third-party cards, **do not** add anything here unless a card dev has made a special json file for this you can point to, putting in a URL directly to a card here will not work, and can potentially cause the component to fail._

**Comment by ludeeus** [comment]
Did it work better when you removed those?

**Comment by edoardop13** [comment]
Yes, now the cards are seen and does not give me more than can not find the custom card
