### ISSUE TITLE
Cannot see any custom component

### ISSUE THREAD

**Issue by ManuelAbril** [custom-cards/tracker-card#55]
Hi,

I cannot see any custom component. There are two errors:

- No sensor.custom_component_tracker under dev-state.
- Cannot finish the service customer_updater.check_all. I have this log:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/websocket_api/commands.py", line 122, in handle_call_service
    connection.context(msg))
  File "/usr/local/lib/python3.7/site-packages/homeassistant/core.py", line 1138, in async_call
    self._execute_service(handler, service_call))
  File "/usr/local/lib/python3.7/site-packages/homeassistant/core.py", line 1160, in _execute_service
    await handler.func(service_call)
  File "/config/custom_components/custom_updater/__init__.py", line 110, in check_all_service
    await components_controller.cache_versions()
  File "/config/custom_components/custom_updater/__init__.py", line 222, in cache_versions
    information = await self.pyupdate.get_sensor_data(True)
  File "/config/deps/lib/python3.7/site-packages/pyupdate/ha_custom/custom_components.py", line 56, in get_sensor_data
    components = await self.get_info_all_components(force)
  File "/config/deps/lib/python3.7/site-packages/pyupdate/ha_custom/custom_components.py", line 41, in get_info_all_components
    entry[attr] = component[attr]
TypeError: string indices must be integers
```

My current configuration is:

configuration.yaml
```
custom_updater:
  show_installable: True
  track:
    - components
    - cards
    - python_scripts
  component_urls:
    - https://raw.githubusercontent.com/keatontaylor/alexa_media_player/master/custom_components.json
    - https://raw.githubusercontent.com/smartHomeHub/SmartIR/master/version.json
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
    - https://raw.githubusercontent.com/iammexx/home-assistant-config/master/ui/darksky/version.json
```

ui-lovelace.yaml
```
    - type: custom:tracker-card
      trackers:
      - sensor.custom_card_tracker
      - sensor.custom_component_tracker
      title: Actualizaciones
      name_text: Nombre
      current_text: Actual
      available_text: Disponible
      check_text: Comprobar
      update_all_text: Actualizar
```

**Comment by ManuelAbril** [comment]
Sorry, there is something wrong in those component_urls. I close it.
